x = (input('Digite algo:'))
print('O tipo primitivo desse valor é:', type(x))
print('Só tem espaços? ', x.isspace())
print('É número? ', x.isnumeric())
print('É alfabético? ', x.isalpha())
print('É alfanumérico? ', x.isalnum())
print('Esta em maiúsculas? ', x.isupper())
print('Esta em minúsculas? ', x.islower())
print('Esta capitalizada? ', x.istitle())
